/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import java.awt.Color;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;


/**
 *
 * @author instructor
 */
public class CrearUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CrearUsuario
     */
    Menu ventanaMenu;
    
    public CrearUsuario(Menu ventanaMenu) {
        this.ventanaMenu=ventanaMenu;
        
        initComponents();
        initAlternativeComponents();
    }
    
    public void initAlternativeComponents(){
        setLocationRelativeTo(null);
        setIconImage(getToolkit().createImage(ClassLoader.getSystemResource("imagenes/crear_usuario.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_crearUser = new javax.swing.JPanel();
        label_CrearUser = new javax.swing.JLabel();
        panel_DatosUser = new javax.swing.JPanel();
        etq_cedulaUser = new javax.swing.JLabel();
        campo_cedulaUser = new javax.swing.JTextField();
        etq_nombres = new javax.swing.JLabel();
        campo_nombreUser = new javax.swing.JTextField();
        etq_apellidoUser = new javax.swing.JLabel();
        campo_apellidoUser = new javax.swing.JTextField();
        etq_telefonoUser = new javax.swing.JLabel();
        campo_telefonoUser = new javax.swing.JTextField();
        etq_direccionUser = new javax.swing.JLabel();
        campo_direccionUser = new javax.swing.JTextField();
        etq_emailUser = new javax.swing.JLabel();
        campo_emailUser = new javax.swing.JTextField();
        btn_cancelarUser = new javax.swing.JButton();
        btn_registrarUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Registrar Usuario");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        panel_crearUser.setBackground(new java.awt.Color(204, 204, 204));

        label_CrearUser.setBackground(new java.awt.Color(0, 0, 0));
        label_CrearUser.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        label_CrearUser.setForeground(new java.awt.Color(0, 0, 0));
        label_CrearUser.setText("CREAR USUARIO");

        javax.swing.GroupLayout panel_crearUserLayout = new javax.swing.GroupLayout(panel_crearUser);
        panel_crearUser.setLayout(panel_crearUserLayout);
        panel_crearUserLayout.setHorizontalGroup(
            panel_crearUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_crearUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_CrearUser)
                .addGap(97, 97, 97))
        );
        panel_crearUserLayout.setVerticalGroup(
            panel_crearUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_crearUserLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(label_CrearUser)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panel_DatosUser.setBackground(new java.awt.Color(255, 255, 255));

        etq_cedulaUser.setBackground(new java.awt.Color(0, 0, 0));
        etq_cedulaUser.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        etq_cedulaUser.setForeground(new java.awt.Color(0, 0, 0));
        etq_cedulaUser.setText("CEDULA");

        campo_cedulaUser.setBackground(new java.awt.Color(255, 255, 255));
        campo_cedulaUser.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N

        etq_nombres.setBackground(new java.awt.Color(0, 0, 0));
        etq_nombres.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        etq_nombres.setForeground(new java.awt.Color(0, 0, 0));
        etq_nombres.setText("NOMBRES");

        campo_nombreUser.setBackground(new java.awt.Color(255, 255, 255));
        campo_nombreUser.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N

        etq_apellidoUser.setBackground(new java.awt.Color(0, 0, 0));
        etq_apellidoUser.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        etq_apellidoUser.setForeground(new java.awt.Color(0, 0, 0));
        etq_apellidoUser.setText("APELLIDOS");

        campo_apellidoUser.setBackground(new java.awt.Color(255, 255, 255));
        campo_apellidoUser.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N

        etq_telefonoUser.setBackground(new java.awt.Color(0, 0, 0));
        etq_telefonoUser.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        etq_telefonoUser.setForeground(new java.awt.Color(0, 0, 0));
        etq_telefonoUser.setText("TELEFONO");

        campo_telefonoUser.setBackground(new java.awt.Color(255, 255, 255));
        campo_telefonoUser.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N

        etq_direccionUser.setBackground(new java.awt.Color(0, 0, 0));
        etq_direccionUser.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        etq_direccionUser.setForeground(new java.awt.Color(0, 0, 0));
        etq_direccionUser.setText("DIRECCION");

        campo_direccionUser.setBackground(new java.awt.Color(255, 255, 255));
        campo_direccionUser.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N

        etq_emailUser.setBackground(new java.awt.Color(0, 0, 0));
        etq_emailUser.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        etq_emailUser.setForeground(new java.awt.Color(0, 0, 0));
        etq_emailUser.setText("EMAIL");

        campo_emailUser.setBackground(new java.awt.Color(255, 255, 255));
        campo_emailUser.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N

        btn_cancelarUser.setBackground(new java.awt.Color(255, 0, 0));
        btn_cancelarUser.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_cancelarUser.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelarUser.setText("CANCELAR");
        btn_cancelarUser.setFocusable(false);
        btn_cancelarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarUserActionPerformed(evt);
            }
        });

        btn_registrarUser.setBackground(new java.awt.Color(153, 255, 0));
        btn_registrarUser.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_registrarUser.setForeground(new java.awt.Color(0, 0, 0));
        btn_registrarUser.setText("REGISTRAR");
        btn_registrarUser.setFocusable(false);
        btn_registrarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_DatosUserLayout = new javax.swing.GroupLayout(panel_DatosUser);
        panel_DatosUser.setLayout(panel_DatosUserLayout);
        panel_DatosUserLayout.setHorizontalGroup(
            panel_DatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_DatosUserLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel_DatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_DatosUserLayout.createSequentialGroup()
                        .addComponent(etq_direccionUser)
                        .addGap(28, 28, 28)
                        .addComponent(campo_direccionUser))
                    .addGroup(panel_DatosUserLayout.createSequentialGroup()
                        .addComponent(etq_apellidoUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(campo_apellidoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_DatosUserLayout.createSequentialGroup()
                        .addGroup(panel_DatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etq_cedulaUser)
                            .addComponent(etq_nombres))
                        .addGap(44, 44, 44)
                        .addGroup(panel_DatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campo_nombreUser)
                            .addComponent(campo_cedulaUser)))
                    .addGroup(panel_DatosUserLayout.createSequentialGroup()
                        .addGroup(panel_DatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etq_telefonoUser)
                            .addComponent(etq_emailUser))
                        .addGap(40, 40, 40)
                        .addGroup(panel_DatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campo_telefonoUser)
                            .addComponent(campo_emailUser))))
                .addContainerGap())
            .addGroup(panel_DatosUserLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(btn_cancelarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_registrarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_DatosUserLayout.setVerticalGroup(
            panel_DatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_DatosUserLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panel_DatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campo_cedulaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etq_cedulaUser))
                .addGap(8, 8, 8)
                .addGroup(panel_DatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etq_nombres)
                    .addComponent(campo_nombreUser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_DatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etq_apellidoUser)
                    .addComponent(campo_apellidoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_DatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etq_telefonoUser)
                    .addComponent(campo_telefonoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_DatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etq_direccionUser)
                    .addComponent(campo_direccionUser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_DatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etq_emailUser)
                    .addComponent(campo_emailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(panel_DatosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_registrarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_crearUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_DatosUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_crearUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_DatosUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarUserActionPerformed
        this.ventanaMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_cancelarUserActionPerformed

    private void btn_registrarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarUserActionPerformed
                                                 
        String cedula = campo_cedulaUser.getText();
        String nombres = campo_nombreUser.getText();
        String apellidos = campo_apellidoUser.getText();
        String direccion = campo_direccionUser.getText();
        String telefono = campo_telefonoUser.getText();
        String email = campo_emailUser.getText();
        
        if (!cedula.equals("") && !nombres.equals("") && !apellidos.equals("") && !direccion.equals("") && !telefono.equals("") && !email.equals("") ) {
            Persona temporal = new Persona(cedula, nombres, apellidos, telefono, direccion, email);
            this.ventanaMenu.listaPersonas[ this.ventanaMenu.indexPersona ] = temporal;
            this.ventanaMenu.indexPersona++;
            
            this.ventanaMenu.setVisible(true);
            //this.ventanaMenu.alertCreacionUsuario();
            dispose();
        }else{
            System.out.println("TODOS LOS CAMPOS SON OBLIGATORIOS");
            validarTodosInputs();
        }
    }//GEN-LAST:event_btn_registrarUserActionPerformed

    public void validarTodosInputs(){
        validarInput(campo_emailUser);
        validarInput(campo_direccionUser);
        validarInput(campo_telefonoUser);
        validarInput(campo_apellidoUser);
        validarInput(campo_nombreUser);
        validarInput(campo_cedulaUser);
    }
    
    public void validarInput(JTextField campo){
        if (campo.getText().equals("")) {
            LineBorder borderFalse = new LineBorder(Color.RED, 1, true);
            campo.setBorder(borderFalse);
            campo.requestFocus();
        }else{
            LineBorder borderFalse = new LineBorder(Color.GREEN, 1, true);
            campo.setBorder(borderFalse);
        }
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelarUser;
    private javax.swing.JButton btn_registrarUser;
    private javax.swing.JTextField campo_apellidoUser;
    private javax.swing.JTextField campo_cedulaUser;
    private javax.swing.JTextField campo_direccionUser;
    private javax.swing.JTextField campo_emailUser;
    private javax.swing.JTextField campo_nombreUser;
    private javax.swing.JTextField campo_telefonoUser;
    private javax.swing.JLabel etq_apellidoUser;
    private javax.swing.JLabel etq_cedulaUser;
    private javax.swing.JLabel etq_direccionUser;
    private javax.swing.JLabel etq_emailUser;
    private javax.swing.JLabel etq_nombres;
    private javax.swing.JLabel etq_telefonoUser;
    private javax.swing.JLabel label_CrearUser;
    private javax.swing.JPanel panel_DatosUser;
    private javax.swing.JPanel panel_crearUser;
    // End of variables declaration//GEN-END:variables
}
