/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

/**
 *
 * @author marbyluci
 */
public class EliminarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form EliminarUsuario
     */
    
    Menu ventanaMenu;
    public EliminarUsuario(Menu ventanaMenu) {
        
        this.ventanaMenu = ventanaMenu;
        initComponents();
        initAlternativeComponents();
    }
    
    public void initAlternativeComponents(){
        setLocationRelativeTo(null);
        setIconImage(getToolkit().createImage(ClassLoader.getSystemResource("imagenes/eliminar_usuario.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etq_modUser = new javax.swing.JLabel();
        panel_EliminarUser = new javax.swing.JPanel();
        labe_EliminarUser = new javax.swing.JLabel();
        panel_BuscarUserDEL = new javax.swing.JPanel();
        etq_cedulaDEL = new javax.swing.JLabel();
        campo_BuscarCedulaDEL = new javax.swing.JTextField();
        btn_buscarDEL = new javax.swing.JButton();
        panel_DatosUserDEL = new javax.swing.JPanel();
        etq_buscarDEL = new javax.swing.JLabel();
        etq_nombreDEL = new javax.swing.JLabel();
        campo_nombreDEL = new javax.swing.JTextField();
        etq_apellidoDEL = new javax.swing.JLabel();
        campo_apellidoDEL = new javax.swing.JTextField();
        etq_CeduDEL = new javax.swing.JLabel();
        campo_cedulaDEL = new javax.swing.JTextField();
        btn_eliminarDEL = new javax.swing.JButton();
        btn_cancelaDEL = new javax.swing.JButton();

        etq_modUser.setBackground(new java.awt.Color(0, 0, 0));
        etq_modUser.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        etq_modUser.setText("MODIFICAR USUARIO");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel_EliminarUser.setBackground(new java.awt.Color(204, 204, 204));

        labe_EliminarUser.setBackground(new java.awt.Color(0, 0, 0));
        labe_EliminarUser.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        labe_EliminarUser.setText("ELIMINAR USUARIO");

        javax.swing.GroupLayout panel_EliminarUserLayout = new javax.swing.GroupLayout(panel_EliminarUser);
        panel_EliminarUser.setLayout(panel_EliminarUserLayout);
        panel_EliminarUserLayout.setHorizontalGroup(
            panel_EliminarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_EliminarUserLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(labe_EliminarUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_EliminarUserLayout.setVerticalGroup(
            panel_EliminarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_EliminarUserLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labe_EliminarUser)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panel_BuscarUserDEL.setBackground(new java.awt.Color(0, 204, 204));

        etq_cedulaDEL.setBackground(new java.awt.Color(255, 255, 255));
        etq_cedulaDEL.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        etq_cedulaDEL.setText("CEDULA");

        campo_BuscarCedulaDEL.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N

        btn_buscarDEL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_buscarDEL.setText("BUSCAR");
        btn_buscarDEL.setFocusable(false);
        btn_buscarDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarDELActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_BuscarUserDELLayout = new javax.swing.GroupLayout(panel_BuscarUserDEL);
        panel_BuscarUserDEL.setLayout(panel_BuscarUserDELLayout);
        panel_BuscarUserDELLayout.setHorizontalGroup(
            panel_BuscarUserDELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BuscarUserDELLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(etq_cedulaDEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campo_BuscarCedulaDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_buscarDEL)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panel_BuscarUserDELLayout.setVerticalGroup(
            panel_BuscarUserDELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BuscarUserDELLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel_BuscarUserDELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_BuscarCedulaDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarDEL)
                    .addComponent(etq_cedulaDEL))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panel_DatosUserDEL.setBackground(new java.awt.Color(255, 255, 255));
        panel_DatosUserDEL.setForeground(new java.awt.Color(255, 255, 255));

        etq_buscarDEL.setBackground(new java.awt.Color(0, 0, 0));
        etq_buscarDEL.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        etq_buscarDEL.setText("Buscando Usuario...");

        etq_nombreDEL.setBackground(new java.awt.Color(0, 0, 0));
        etq_nombreDEL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        etq_nombreDEL.setText("Nombres:");

        campo_nombreDEL.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N

        etq_apellidoDEL.setBackground(new java.awt.Color(0, 0, 0));
        etq_apellidoDEL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        etq_apellidoDEL.setText("Apellidos:");

        campo_apellidoDEL.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N

        etq_CeduDEL.setBackground(new java.awt.Color(0, 0, 0));
        etq_CeduDEL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        etq_CeduDEL.setText("Cedula:");

        campo_cedulaDEL.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N

        btn_eliminarDEL.setBackground(new java.awt.Color(255, 204, 0));
        btn_eliminarDEL.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_eliminarDEL.setText("ELIMINAR");
        btn_eliminarDEL.setFocusable(false);
        btn_eliminarDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarDELActionPerformed(evt);
            }
        });

        btn_cancelaDEL.setBackground(new java.awt.Color(0, 0, 0));
        btn_cancelaDEL.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_cancelaDEL.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelaDEL.setText("CANCELAR");
        btn_cancelaDEL.setFocusable(false);
        btn_cancelaDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelaDELActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_DatosUserDELLayout = new javax.swing.GroupLayout(panel_DatosUserDEL);
        panel_DatosUserDEL.setLayout(panel_DatosUserDELLayout);
        panel_DatosUserDELLayout.setHorizontalGroup(
            panel_DatosUserDELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_DatosUserDELLayout.createSequentialGroup()
                .addGroup(panel_DatosUserDELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_DatosUserDELLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etq_buscarDEL))
                    .addGroup(panel_DatosUserDELLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(panel_DatosUserDELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_DatosUserDELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panel_DatosUserDELLayout.createSequentialGroup()
                                    .addComponent(etq_nombreDEL)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(campo_nombreDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panel_DatosUserDELLayout.createSequentialGroup()
                                    .addComponent(etq_apellidoDEL)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(campo_apellidoDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel_DatosUserDELLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(etq_CeduDEL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campo_cedulaDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_DatosUserDELLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_cancelaDEL)
                .addGap(18, 18, 18)
                .addComponent(btn_eliminarDEL)
                .addGap(99, 99, 99))
        );
        panel_DatosUserDELLayout.setVerticalGroup(
            panel_DatosUserDELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_DatosUserDELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etq_buscarDEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_DatosUserDELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etq_nombreDEL)
                    .addComponent(campo_nombreDEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(panel_DatosUserDELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etq_apellidoDEL)
                    .addComponent(campo_apellidoDEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_DatosUserDELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_cedulaDEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etq_CeduDEL))
                .addGap(40, 40, 40)
                .addGroup(panel_DatosUserDELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_eliminarDEL)
                    .addComponent(btn_cancelaDEL))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_EliminarUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_BuscarUserDEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_DatosUserDEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_EliminarUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_BuscarUserDEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_DatosUserDEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    int posicioneliminar;
    private void btn_buscarDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarDELActionPerformed
        String numeroCedula = campo_BuscarCedulaDEL.getText();
        boolean usuarioEncontrado = false;
        for (int i = 0; i < this.ventanaMenu.listaPersonas.length; i++) {
            posicioneliminar=i;
            if (this.ventanaMenu.listaPersonas[i] != null && this.ventanaMenu.listaPersonas[i].getCedula().equals(numeroCedula)) {
                etq_buscarDEL.setText("Usuario Encontrado");
                campo_nombreDEL.setText(this.ventanaMenu.listaPersonas[i].getNombres());
                campo_apellidoDEL.setText(this.ventanaMenu.listaPersonas[i].getApellidos());
                campo_cedulaDEL.setText(this.ventanaMenu.listaPersonas[i].getCedula());
                    
                campo_nombreDEL.setEnabled(false);
                campo_apellidoDEL.setEnabled(false);
                campo_cedulaDEL.setEnabled(false);
                    //posicionModificar = i;
  
                usuarioEncontrado = true; // El usuario ha sido encontrado
                break; // Salir del ciclo una vez encontrado
            }
        }

        if (!usuarioEncontrado) {
            etq_buscarDEL.setText("Usuario No Encontrado");
            campo_nombreDEL.setText("");
            campo_apellidoDEL.setText("");
            campo_cedulaDEL.setText("");
        }
          
    }//GEN-LAST:event_btn_buscarDELActionPerformed

    private void btn_cancelaDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelaDELActionPerformed
        this.ventanaMenu.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_btn_cancelaDELActionPerformed

    private void btn_eliminarDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarDELActionPerformed
        this.ventanaMenu.listaPersonas[posicioneliminar] = null;

        // Desplazar las siguientes posiciones hacia atrás
        for (int i = posicioneliminar + 1; i < this.ventanaMenu.listaPersonas.length; i++) {
            this.ventanaMenu.listaPersonas[i - 1] = this.ventanaMenu.listaPersonas[i];
        }
        this.ventanaMenu.listaPersonas[this.ventanaMenu.listaPersonas.length - 1] = null;
        System.out.println("Usuario Eliminado");
        campo_nombreDEL.setText("");
        campo_apellidoDEL.setText("");
        campo_cedulaDEL.setText("");
        campo_nombreDEL.setEnabled(true);
        campo_apellidoDEL.setEnabled(true);
        campo_cedulaDEL.setEnabled(true);

        etq_buscarDEL.setText("Usuario Eliminado");
    }//GEN-LAST:event_btn_eliminarDELActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscarDEL;
    private javax.swing.JButton btn_cancelaDEL;
    private javax.swing.JButton btn_eliminarDEL;
    private javax.swing.JTextField campo_BuscarCedulaDEL;
    private javax.swing.JTextField campo_apellidoDEL;
    private javax.swing.JTextField campo_cedulaDEL;
    private javax.swing.JTextField campo_nombreDEL;
    private javax.swing.JLabel etq_CeduDEL;
    private javax.swing.JLabel etq_apellidoDEL;
    private javax.swing.JLabel etq_buscarDEL;
    private javax.swing.JLabel etq_cedulaDEL;
    private javax.swing.JLabel etq_modUser;
    private javax.swing.JLabel etq_nombreDEL;
    private javax.swing.JLabel labe_EliminarUser;
    private javax.swing.JPanel panel_BuscarUserDEL;
    private javax.swing.JPanel panel_DatosUserDEL;
    private javax.swing.JPanel panel_EliminarUser;
    // End of variables declaration//GEN-END:variables
}
