/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

/**
 *
 * @author instructor
 */
public class ModificarUsuario extends javax.swing.JFrame {

    Menu ventanaMenu;
    public ModificarUsuario(Menu ventanaMenu) {
        
        this.ventanaMenu = ventanaMenu;
        initComponents();
        initAlternativeComponents();
    }
    
    public void initAlternativeComponents(){
        setLocationRelativeTo(null);
        setIconImage(getToolkit().createImage(ClassLoader.getSystemResource("imagenes/editar_usuario.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_modUser = new javax.swing.JPanel();
        etq_modUser = new javax.swing.JLabel();
        panel_BuscarUser = new javax.swing.JPanel();
        etq_cedula = new javax.swing.JLabel();
        campo_busCedula = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        panel_datosUser = new javax.swing.JPanel();
        etq_encontrado = new javax.swing.JLabel();
        etq_nombre = new javax.swing.JLabel();
        campo_nombre = new javax.swing.JTextField();
        etq_apellido = new javax.swing.JLabel();
        campo_apellido = new javax.swing.JTextField();
        etq_telefono = new javax.swing.JLabel();
        campo_telefono = new javax.swing.JTextField();
        etq_direccion = new javax.swing.JLabel();
        campo_direccion = new javax.swing.JTextField();
        etq_email = new javax.swing.JLabel();
        campo_email = new javax.swing.JTextField();
        btn_cancelar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MODIFICAR USUARIO");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        panel_modUser.setBackground(new java.awt.Color(204, 204, 204));

        etq_modUser.setBackground(new java.awt.Color(0, 0, 0));
        etq_modUser.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        etq_modUser.setForeground(new java.awt.Color(0, 0, 0));
        etq_modUser.setText("MODIFICAR USUARIO");

        javax.swing.GroupLayout panel_modUserLayout = new javax.swing.GroupLayout(panel_modUser);
        panel_modUser.setLayout(panel_modUserLayout);
        panel_modUserLayout.setHorizontalGroup(
            panel_modUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modUserLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(etq_modUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_modUserLayout.setVerticalGroup(
            panel_modUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modUserLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(etq_modUser)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panel_BuscarUser.setBackground(new java.awt.Color(204, 255, 51));

        etq_cedula.setBackground(new java.awt.Color(0, 0, 0));
        etq_cedula.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        etq_cedula.setForeground(new java.awt.Color(0, 0, 0));
        etq_cedula.setText("CEDULA");

        campo_busCedula.setBackground(new java.awt.Color(255, 255, 255));
        campo_busCedula.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N

        btn_buscar.setBackground(new java.awt.Color(255, 255, 255));
        btn_buscar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(0, 0, 0));
        btn_buscar.setText("BUSCAR");
        btn_buscar.setFocusable(false);
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_BuscarUserLayout = new javax.swing.GroupLayout(panel_BuscarUser);
        panel_BuscarUser.setLayout(panel_BuscarUserLayout);
        panel_BuscarUserLayout.setHorizontalGroup(
            panel_BuscarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BuscarUserLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(etq_cedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_busCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_buscar)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panel_BuscarUserLayout.setVerticalGroup(
            panel_BuscarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BuscarUserLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_BuscarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etq_cedula)
                    .addComponent(campo_busCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panel_datosUser.setBackground(new java.awt.Color(255, 255, 255));
        panel_datosUser.setForeground(new java.awt.Color(255, 255, 255));

        etq_encontrado.setBackground(new java.awt.Color(0, 0, 0));
        etq_encontrado.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        etq_encontrado.setForeground(new java.awt.Color(0, 0, 0));
        etq_encontrado.setText("Buscando Usuario...");

        etq_nombre.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        etq_nombre.setForeground(new java.awt.Color(0, 0, 0));
        etq_nombre.setText("Nombres:");

        campo_nombre.setBackground(new java.awt.Color(255, 255, 255));
        campo_nombre.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        campo_nombre.setForeground(new java.awt.Color(0, 0, 0));

        etq_apellido.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        etq_apellido.setForeground(new java.awt.Color(0, 0, 0));
        etq_apellido.setText("Apellidos:");

        campo_apellido.setBackground(new java.awt.Color(255, 255, 255));
        campo_apellido.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        campo_apellido.setForeground(new java.awt.Color(0, 0, 0));

        etq_telefono.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        etq_telefono.setForeground(new java.awt.Color(0, 0, 0));
        etq_telefono.setText("Telefono:");

        campo_telefono.setBackground(new java.awt.Color(255, 255, 255));
        campo_telefono.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        campo_telefono.setForeground(new java.awt.Color(0, 0, 0));

        etq_direccion.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        etq_direccion.setForeground(new java.awt.Color(0, 0, 0));
        etq_direccion.setText("Direccion:");

        campo_direccion.setBackground(new java.awt.Color(255, 255, 255));
        campo_direccion.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        campo_direccion.setForeground(new java.awt.Color(0, 0, 0));

        etq_email.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        etq_email.setForeground(new java.awt.Color(0, 0, 0));
        etq_email.setText("Email:");

        campo_email.setBackground(new java.awt.Color(255, 255, 255));
        campo_email.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        campo_email.setForeground(new java.awt.Color(0, 0, 0));

        btn_cancelar.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(0, 0, 0));
        btn_cancelar.setText("CANCELAR");
        btn_cancelar.setFocusable(false);
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_modificar.setBackground(new java.awt.Color(255, 255, 255));
        btn_modificar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_modificar.setForeground(new java.awt.Color(0, 0, 0));
        btn_modificar.setText("MODIFICAR");
        btn_modificar.setFocusable(false);

        javax.swing.GroupLayout panel_datosUserLayout = new javax.swing.GroupLayout(panel_datosUser);
        panel_datosUser.setLayout(panel_datosUserLayout);
        panel_datosUserLayout.setHorizontalGroup(
            panel_datosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datosUserLayout.createSequentialGroup()
                .addGroup(panel_datosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_datosUserLayout.createSequentialGroup()
                        .addGroup(panel_datosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_datosUserLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(etq_encontrado)
                                .addGap(76, 76, 76))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_datosUserLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(panel_datosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etq_telefono)
                                    .addComponent(etq_direccion)
                                    .addComponent(etq_email)
                                    .addComponent(etq_apellido)
                                    .addComponent(etq_nombre))
                                .addGap(23, 23, 23)))
                        .addGroup(panel_datosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campo_nombre)
                            .addComponent(campo_apellido)
                            .addComponent(campo_telefono)
                            .addComponent(campo_direccion)
                            .addComponent(campo_email, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))
                    .addGroup(panel_datosUserLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btn_cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_modificar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_datosUserLayout.setVerticalGroup(
            panel_datosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datosUserLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panel_datosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_datosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campo_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etq_telefono))
                    .addGroup(panel_datosUserLayout.createSequentialGroup()
                        .addComponent(etq_encontrado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_datosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etq_nombre)
                            .addComponent(campo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_datosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etq_apellido)
                            .addComponent(campo_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)))
                .addGap(22, 22, 22)
                .addGroup(panel_datosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etq_direccion))
                .addGap(18, 18, 18)
                .addGroup(panel_datosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etq_email)
                    .addComponent(campo_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(panel_datosUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_modificar))
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_modUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_datosUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_BuscarUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_modUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_BuscarUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_datosUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        String numeroCedula = campo_busCedula.getText();
        boolean usuarioEncontrado = false;

        for (int i = 0; i < this.ventanaMenu.listaPersonas.length; i++) {
            if (this.ventanaMenu.listaPersonas[i] != null && this.ventanaMenu.listaPersonas[i].getCedula().equals(numeroCedula)) {
                etq_encontrado.setText("Usuario Encontrado");
                campo_nombre.setText(this.ventanaMenu.listaPersonas[i].getNombres());
                campo_apellido.setText(this.ventanaMenu.listaPersonas[i].getApellidos());
                campo_telefono.setText(this.ventanaMenu.listaPersonas[i].getTelefono());
                campo_direccion.setText(this.ventanaMenu.listaPersonas[i].getDirreccion());
                campo_email.setText(this.ventanaMenu.listaPersonas[i].getEmail());
                usuarioEncontrado = true; // El usuario ha sido encontrado
                break; // Salir del ciclo una vez encontrado
            }
        }

        if (!usuarioEncontrado) {
            etq_encontrado.setText("Usuario No Encontrado");
            campo_nombre.setText("");
            campo_apellido.setText("");
            campo_telefono.setText("");
            campo_direccion.setText("");
            campo_email.setText("");
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.ventanaMenu.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JTextField campo_apellido;
    private javax.swing.JTextField campo_busCedula;
    private javax.swing.JTextField campo_direccion;
    private javax.swing.JTextField campo_email;
    private javax.swing.JTextField campo_nombre;
    private javax.swing.JTextField campo_telefono;
    private javax.swing.JLabel etq_apellido;
    private javax.swing.JLabel etq_cedula;
    private javax.swing.JLabel etq_direccion;
    private javax.swing.JLabel etq_email;
    private javax.swing.JLabel etq_encontrado;
    private javax.swing.JLabel etq_modUser;
    private javax.swing.JLabel etq_nombre;
    private javax.swing.JLabel etq_telefono;
    private javax.swing.JPanel panel_BuscarUser;
    private javax.swing.JPanel panel_datosUser;
    private javax.swing.JPanel panel_modUser;
    // End of variables declaration//GEN-END:variables
}
